const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const shots=fs.mkdtempSync(path.join(os.tmpdir(),'beta-motion-'));
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try{
 const context=await browser.newContext({viewport:{width:390,height:844},colorScheme:'light',reducedMotion:'no-preference'});
 await context.addInitScript(()=>{localStorage.setItem('way_lk_token','test');sessionStorage.setItem('way_intro_v4','1');localStorage.setItem('way_home_coach_v2','1');});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const me={user:{name:'Александр',username:'alex'},balance_rub:360,topup_min:50,topup_max:10000,topup_step:50,balance_enabled:true,days_left:30,day_price_rub:6,vpn_day_price_rub:6,has_paid_topup:true,has_access:true,trial_available:false,promo_enabled:true,notification_settings_available:true,devices:[],legal:{offer:'#',privacy:'#'},invite_url:'https://t.me/test?start=ref_1',referral_program_enabled:true,referral_terms:{note:'50 ₽ за друга и 5% от пополнений'},topup_plans:[{code:'topup_300',title:'300 ₽',rub:300,amount:300}],trust:{enabled:false}};
 await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.host!=='cabinet.test')return route.fulfill({body:'',contentType:'application/javascript'});if(url.pathname.startsWith('/api/'))return route.fulfill({json:url.pathname==='/api/me'?me:{ok:true,items:[]}});const rel=url.pathname==='/'?'index.html':url.pathname.replace(/^\/(static\/)?/,'');const file=path.resolve(__dirname,'../../webapp',rel);return fs.existsSync(file)?route.fulfill({path:file}):route.fulfill({status:404,body:''});});

 await page.goto('http://cabinet.test/');await page.locator('#app:not(.hidden)').waitFor();
 await page.evaluate(()=>{WayAppearance.choose('design','modern');WayAppearance.choose('theme','dark');openHome();});
 const motion = await page.evaluate(()=>document.querySelector('#view-home .status-card').getAnimations().map(a=>a.effect.getTiming()));
 assert.ok(motion.some(a=>a.duration===380),'home cards must animate');
 await page.evaluate(()=>{openTopup();openHome();openSettings();});
 assert.equal(await page.locator('#view-settings').isVisible(),true);
 assert.equal(await page.locator('#view-home .status-card').evaluate(el=>el.getAnimations().length),0,'old view animations cancelled');
 await page.waitForFunction(()=>document.querySelector('#view-settings').getAnimations({subtree:true}).every(a=>a.playState!=='running'));
 assert.equal(await page.evaluate(()=>document.querySelector('#view-settings').getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0,'finite animations settle');
 await page.evaluate(()=>{window.__me.faq=[{q:'Как подключиться?',a:'Добавьте устройство, установите приложение и откройте в нём ссылку подписки.'}];openFaq('home');});
 await page.waitForTimeout(600);await page.locator('#faqList button').click();await page.waitForTimeout(320);
 const expanded=await page.locator('.faq-a').boundingBox();assert.ok(expanded.height>20);
 await page.locator('#faqList button').click();await page.waitForTimeout(320);
 await page.waitForFunction(()=>document.querySelector('.faq-a').getBoundingClientRect().height===0);
 const collapsed=await page.locator('.faq-a').boundingBox();assert.equal(collapsed.height,0);
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.evaluate(()=>openHome());
 assert.equal(await page.locator('#view-home .status-card').evaluate(el=>el.getAnimations().length),0,'reduced motion skips WAAPI');
 await page.evaluate(()=>openFaq('home'));await page.locator('#faqList button').click();
 assert.ok(await page.locator('.faq-a').isVisible(),'reduced motion still opens answers');
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.evaluate(()=>{openHome();WayAppearance.choose('design','classic');});
 assert.equal(await page.evaluate(()=>document.documentElement.dataset.design),'modern','old preference cannot restore classic');
 await page.evaluate(()=>{WayAppearance.choose('design','modern');openHome();});await page.waitForTimeout(600);
 await page.evaluate(()=>openSettings());await page.waitForTimeout(100);await page.screenshot({path:path.join(shots,'transition.png'),animations:'allow'});await page.waitForTimeout(600);
 await page.screenshot({path:path.join(shots,'settled.png')});
 await page.setViewportSize({width:320,height:740});
 await page.evaluate(()=>{window.__me.user.name='Очень длинное имя пользователя';window.__me.user.username='very_long_username_without_any_spaces_123456789';window.__me.user.photo='/missing-avatar.png';paint(window.__me);openHome();});
 await page.waitForFunction(()=>document.querySelector('#avatar').naturalWidth>0 && document.querySelector('#avatar').getAttribute('src').includes('profile-placeholder'));
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'long profile must not overflow');
 await page.waitForFunction(()=>document.querySelector('#view-home').getAnimations({subtree:true}).every(a=>a.playState!=='running'));
 await page.screenshot({path:path.join(shots,'profile-small.png')});
 await page.evaluate(()=>{openTopup();setMainBusy(true);});
 assert.equal(await page.locator('#appMainBtn').getAttribute('aria-busy'),'true');
 assert.equal(await page.locator('#appMainBtn').isDisabled(),true);
 assert.equal(await page.locator('#appMainBtn').evaluate(el=>getComputedStyle(el,'::after').animationName),'beta-working');
 await page.emulateMedia({reducedMotion:'reduce'});
 assert.equal(await page.locator('#appMainBtn').evaluate(el=>getComputedStyle(el,'::after').animationName),'none');
 await page.evaluate(()=>setMain('Продолжить',()=>{}));
 assert.equal(await page.locator('#appMainBtn').getAttribute('aria-busy'),'false');
 assert.equal(await page.locator('#appMainBtn').isEnabled(),true);
 assert.deepEqual(errors,[]);console.log('Motion, fast navigation, FAQ, reduced motion and classic isolation passed. '+shots);
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
